export interface ComponentIndexEntry {
  name: string
  description: string | null
  importPath: string
}

// Optional one-line note shown under a category heading.
const categoryDescriptions: Record<string, string> = {
  input: "Form-item controls (inputs, selects, checkboxes, switches, fieldsets).",
}

const header = `<!-- GENERATED by \`bun run generateUiIndex\` in the solid-ui project — do not edit by hand. -->

# solid-ui component index

> Generic UI library, synced into consuming apps under \`./ui\` (read-only there — local edits are overwritten on the next sync). To change a component, edit it in **solid-ui**, or override/extend it under \`src/ui\` in the consuming app.
>
> This index exists so agents can find a component without scanning the tree. Import everything via the \`#ui/...\` alias. Descriptions come from a one-line JSDoc above each export in solid-ui; regenerate with \`bun run generateUiIndex\`.`

export function renderUiIndexMarkdown(byCategory: Record<string, ComponentIndexEntry[]>): string {
  const categories = Object.keys(byCategory).sort()
  const entriesOf = (c: string): ComponentIndexEntry[] => byCategory[c] ?? []
  const total = categories.reduce((sum, c) => sum + entriesOf(c).length, 0)
  const documented = categories.reduce(
    (sum, c) => sum + entriesOf(c).filter((e) => e.description).length,
    0,
  )

  const sections = categories.map((category) => {
    const entries = [...entriesOf(category)].sort((a, b) => a.name.localeCompare(b.name))
    const rows = entries.map((e) => {
      const desc = e.description ? ` — ${e.description}` : ""
      return `- **${e.name}** — \`${e.importPath}\`${desc}`
    })
    const note = categoryDescriptions[category]
    const heading = `## ${category} (${entries.length})`
    return note ? `${heading}\n\n_${note}_\n\n${rows.join("\n")}` : `${heading}\n\n${rows.join("\n")}`
  })

  return `${header}

**${total}** components across **${categories.length}** categories · **${documented}** documented, **${total - documented}** need a JSDoc line.

${sections.join("\n\n")}
`
}
